### ISSUE TITLE
Pressing ALT+Tab while being in citymap breaks everything

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#1027]

**Comment by jokoho48** [comment]
Fixed in Build 731.

**Comment by Gerwanese** [comment]
Unfortunately not completely fixed - currently, pressing ALT+TAB while Voogle Maps is open (and the game paused in my case, maybe it's related?), you will end up in an intermediate state between map and "normal" mode.
Pressing M will bring you fully back to normal mode.

https://user-images.githubusercontent.com/17579552/166582682-2267ac9d-8ac9-48f9-a97a-d0377497d6f6.mp4

**Comment by jokoho48** [comment]
Fixed in Build 732. (did it while the build was running and the change didn't made it)

**Comment by GrayySheep** [comment]
Screenshot from build 732

![Big Ambitions 4_05_2022 5_05_40 pm](https://user-images.githubusercontent.com/104757675/166625695-c3e5c70d-05fc-4ba5-84d3-af99d3b4d302.png)

**Comment by David-Goru** [comment]
Fixed in build 733
