### ISSUE TITLE
Corrupted business (impossible to move objects, access storage or even stop renting)

### ISSUE THREAD

**Issue by Suniver** [hovgaardgames/bigambitions#1102]
### Build number

886

### Bug description

Suddenly after 00:00 passes and when I tried to check my business inventory from the BizMan it was showing the inventory of my second business. When I came inside to check impossible to open the storage shelf, when I try to move it is impossible to place it and I am stuck in "move object mode". If another day passes, the business is considered as missing or having no more stuff to sell even if round shelves are full of gifts. I can shut down the business but nothing changes and it is impossible to cancel the rent.

### Steps to reproduce the bug

Unfortunately I have no idea how this happened and how to reproduce...

### Savegame file

[New Aiden Bradley Save Game 4.txt](https://github.com/hovgaardgames/bigambitions/files/8905644/New.Aiden.Bradley.Save.Game.4.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/77306553/173737001-bc8d15d8-987d-4b04-9f1f-3e18358e53ba.mp4

**Comment by David-Goru** [comment]
Fixed in build 887!

**Comment by viper12344** [comment]
its not fixed...i have the same thing every time i start the 2nd business..my first business then weirds out , you cant drop things you pick up ,cant pick up items from storage shelves , sometimes the sales racks go to zero merch and cant restock...all kinds of stuff happens with worker too. still going as of 6/18
