### ISSUE TITLE
Beta 3 savegame can't be loaded in beta 4 due to new neighborhood

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1138]
### Build number

1002

### Bug description

Loading doesn't work due to error in savegame compatibility fix.

```
NullReferenceException: Object reference not set to an instance of an object
  at Helpers.CityGenerator.SetupResidentialBuildings (Enums.Neighbourhood neighbourhood) [0x00012] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at Helpers.CityGenerator.InitializeCity (Enums.Neighbourhood neighbourhood) [0x00006] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at SaveGameCompatibilityFixes.ApplyCompatibilityFixV996 (GameInstance savegame) [0x00086] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at SaveGameCompatibilityFixes.ApplyAlphaCompatibilityFixes (GameInstance savegame) [0x00150] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at SaveGameManager.Load (SaveGameManager+SaveGameStruct saveGame, System.Boolean loadScene) [0x000a0] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at Scenes.MainMenu.LoadGame.Load (SaveGameManager+SaveGameStruct fileName) [0x00000] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at Scenes.MainMenu.LoadGame+<>c__DisplayClass13_1.<SetUpCharacter>b__9 () [0x00000] in <b733df4461674da284d38fbd8ba54aa8>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00010] in <fbf5779b092846b08cf20985bc90dcd0>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00022] in <fbf5779b092846b08cf20985bc90dcd0>:0 
  at UnityEngine.UI.Button.Press () [0x0001c] in <4730d91f38774a759509d00c23a18133>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00009] in <4730d91f38774a759509d00c23a18133>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <4730d91f38774a759509d00c23a18133>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00067] in <4730d91f38774a759509d00c23a18133>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.InputSystem.UI.InputSystemUIInputModule:ProcessPointerButton(ButtonState&, PointerEventData)
UnityEngine.InputSystem.UI.InputSystemUIInputModule:ProcessPointer(PointerModel&)
UnityEngine.InputSystem.UI.InputSystemUIInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
```

[Player.log](https://github.com/hovgaardgames/bigambitions/files/9122814/Player.log)

### Savegame file

[Build897-RichyRich.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9122813/Build897-RichyRich.hsg.txt)

**Comment by jhovgaard** [comment]
Fixed in build 1007

**Comment by Gerwanese** [comment]
Still not loading in Build 1008.

[Player.log](https://github.com/hovgaardgames/bigambitions/files/9128264/Player.log)

**Comment by jhovgaard** [comment]
Let's try again :) Fixed in build 1009
