### ISSUE TITLE
IRS paying taxes screen goes weird when it's more then a million cuts off last digit on new line

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1224]
### Build number

1013

### Bug description

IRS paying taxes screen goes weird when it's more then a million cuts off last digit on new line

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180293231-54f7a42a-a4c2-47c9-acc4-994503b0dcd0.png)

**Comment by David-Goru** [comment]
Fixed in build 1014

**Comment by rpgforyou** [comment]
Not fixed for the bottem orange part ...
![afbeelding](https://user-images.githubusercontent.com/9866863/180664988-e890cc32-1b51-49d1-b03e-9412d8e526eb.png)
