### ISSUE TITLE
Selecting image on disk for my store logo comes up with a blown up window takes up the entire screen.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1341]
### Build number

1252

### Bug description

Selecting image on disk for my store logo comes up with a blown up window takes up the entire screen.

![afbeelding](https://user-images.githubusercontent.com/9866863/190795086-8c6e168d-ad96-46f8-96cb-af91e66ccc64.png)

**Comment by David-Goru** [comment]
Which is your screen resolution and how much UI scaling have you set?

**Comment by rpgforyou** [comment]
Lol I only see this just now. Sorry I get like thousand mails about you guys closing my tickets haha. Next time @ me on Discord if you wish so I'm aware. 

Resolution 2560x1080
Uiscaling 102 % (apparently ...)

Also when you 'select from disk' one's you'll have the images show in the list. But if I open it a second time no images appear to select and it's the same folder. It's like the second time you click on it, it bugs out?

**Comment by David-Goru** [comment]
Second bug will be fixed in next beta, but I can't reproduce the first one (same UI Scaling and resolution)

![imagen](https://user-images.githubusercontent.com/50799541/191690985-b6b07e94-9a4a-41d0-831e-e770aad4861a.png)

**Comment by David-Goru** [comment]
Fixed in build 1253

**Comment by rpgforyou** [comment]
@David-Goru 
That's a negative for me:
"Second bug will be fixed in next beta, but I can't reproduce the first one (same UI Scaling and resolution)"
Btw is it also possible to like see the images as you can in windows explorer for example?

**Comment by rpgforyou** [comment]
@David-Goru :
BTW I still have this issue when you want to select your logo and you click the first time your folders and images appear in the file browser. If you cancel it and open it again no folder or image shows.

**Comment by David-Goru** [comment]
The file browser have been removed and changed with a more simple approach
