### ISSUE TITLE
Mop will be a box after reloading

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#303]
Build 76

When saving the game while holding a mop in hands, after reloading you will hold a box containing a mop.
Additionally, the original mop is back at it's previous place in the shop, so you will effectively double your mop.

This bug is a bit similar to #278, which I think was just a temporary issue.

[Build75-HolyMop.txt](https://github.com/hovgaardgames/bigambitions-public/files/6795734/Build75-HolyMop.txt)

**Comment by jhovgaard** [comment]
Fixed in build 79

**Comment by Gerwanese** [comment]
Not fully fixed: The mop is not duplicated anymore, but still after reloading you're holding a box in hands.

[Build106-HoldingMop.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903779/Build106-HoldingMop.txt)

**Comment by jhovgaard** [comment]
Workload is around 1-2 days to fix. As the bug is not breaking anything, I'll move it to low priority.

**Comment by jokoho48** [comment]
cant reproduce anymore

**Comment by David-Goru** [comment]
Fixed in build 1837
