### ISSUE TITLE
Car can get stuck on sidewalk

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#753]
### Build number

322

### Bug description

It's possible to bring the car into a position where it can't move anymore. The problem persists even after reloading.

### Savegame file

[Build322-CarStuck.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877690/Build322-CarStuck.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149673719-f63761ba-068a-487b-8c2a-adbde8d00fce.mp4

**Comment by jhovgaard** [comment]
Fixed in build 326

**Comment by Gerwanese** [comment]
Not fully fixed, see this savegame:
[JDcarstuck.json.txt](https://github.com/hovgaardgames/bigambitions/files/7917359/JDcarstuck.json.txt)

For reference see https://community.bigambitionsgame.com/t/car-stuck/654

**Comment by jokoho48** [comment]
Fixed with Beta 4. in situations like this call AutoTowService!
