### ISSUE TITLE
BizMan not updating details for law firm

### ISSUE THREAD

**Issue by rsdworker** [hovgaardgames/bigambitions#793]
### Build number

336 and possibly 337?

### Bug description

the bug is when you go look at lawfirm and see what inside and what the hours however i found one law firm exists BUT when i view bizman - its dont exist - thats very wierd

### Steps to reproduce the bug

go to any Law firms and you find law firm is not exist there even its says its there

### Screenshots or videos

law firm exists on street buts shows closed
![image](https://user-images.githubusercontent.com/6688223/150651569-e4310bab-deba-4c06-88e8-65f4f8687bcf.png)

view on bizman - shows no lawfirm exist in this location
![image](https://user-images.githubusercontent.com/6688223/150651579-21425b3c-33a3-4354-bfe7-165928b4911b.png)

**Comment by Gerwanese** [comment]
Verified in build 337.
The law firm BizMan display doesn't update the screen properly.
As you can see, the building overlay is still visible (top middle in the screenshot).
The "business hour" area will show the details of the last building you selected. If the last one was renting and opening your own building, it will show the "start a business screen" (like in the screenshot). If the last one was some other existing business, it will update the business name but show the business hours of the previously selected one.

https://user-images.githubusercontent.com/17579552/150651890-9cb372d3-0b3c-4f37-ba01-031e32c77a0f.mp4

[Build337-OutlawInLawFirm.json.txt](https://github.com/hovgaardgames/bigambitions/files/7919068/Build337-OutlawInLawFirm.json.txt)

**Comment by rsdworker** [comment]
great its will be fixed :D

**Comment by jokoho48** [comment]
Fixed in Build 339.

**Comment by Gerwanese** [comment]
Still broken in build 340 unfortunately.

[Build340-HostileTakeoverOfLawFirm.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964310/Build340-HostileTakeoverOfLawFirm.json.txt)

![grafik](https://user-images.githubusercontent.com/17579552/151672953-2ee4259f-f7e9-405f-a5b5-ce40fd6042bc.png)

**Comment by jokoho48** [comment]
Fixed in Build 342.
