### ISSUE TITLE
Not Starting work if clicked before shift time

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#81]
Alpha 4 - Build 49

If you are on a workday and head to your store and click on the counter to start work but before your shift it will say "Shift Not Started Yet" with no "Start Working" button, and when your shift starts the button appears which you can click and it looks like you are working, but the message still shows  "Shift Not Started Yet" and you arent working.

**Comment by Gerwanese** [comment]
Confirmed.

Click on the counter before start of working time.
Once working time is reached, the "start working" button automatically shows up but when clicking on it, it still shows "Your shift hasn't started yet."
It seems you still earn money but it only shows up after finishing the shift.

![grafik](https://user-images.githubusercontent.com/17579552/120242560-7710b080-c265-11eb-8dc7-ba71b0fa94ad.png)

**Comment by jhovgaard** [comment]
Fixed in build 61

**Comment by Gerwanese** [comment]
Issue is back in build 243. 🤣 

[Build242-StartWorkBeforeShift.txt](https://github.com/hovgaardgames/bigambitions/files/7447273/Build242-StartWorkBeforeShift.txt)


https://user-images.githubusercontent.com/17579552/139543360-d456f7be-cb56-4e0c-a06d-f6052ec84be3.mp4

**Comment by David-Goru** [comment]
Fixed in build 264
